#!/bin/bash
# 
#    Copyright (C) 2007 Serge van Ginderachter <svg@ginsys.be>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License version 2 as 
#    published by the Free Software Foundation.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#    Or download it from http://www.gnu.org/licenses/old-licenses/gpl-2.0.html

  
#### Modify the following variables according to your installation

# backup_dir - directory to backup to 
zm_backup_path=/opt.bak

# zm_lv - the Logical Volume that contains /opt/zimbra - /opt mount point expected
zm_lv=opt

# vol_group - the Volume Group that contains $zm_lv
zm_vg=data

# zimbra_path - the path beneath the Logical Volume $zm_lv that needs to be synced
zm_path=

# zm_lv_fs - the file system type (ext3, xfs, ...) in /opt/zimbra
zm_lv_fs=ext3

# lvcreate lvremove - path and command for the lvm logical volume creation and deletion command
LVCREATE=/sbin/lvcreate
LVREMOVE=/sbin/lvremove

#### Modify the following variables according to your taste and needs

# zmsnapshot - the snapshot volume name for $zm_lv
zm_snapshot=opt-snapshot

# zmsnapshot_size - size avalable for growing the snapshot - set either this or zm_snapshot_extents
zm_snapshot_size=1G

# zm_snapshot_extents - number of extents avalable for growing the snapshot - set either this or zm_snapshot_size
#zm_snapshot_extents=50%FREE

# zm_snapshot_mnt - zimbra snapshot mount point
zm_snapshot_path=/tmp/opt-snapshot

# rsync verbose set to "v"
# V=v
V=

#  pause at each step if $debug is set to a non-zero string
debug=

#### Following parameters probably shouldn't need to be changed

log_facility=daemon
log_facility_mail=mail
log_level=notice
log_level_err=error
log_tag="$0"

